name: Recent Activity

on:
  schedule:
    - cron: "0 * * * *"   # Runs every hour
  workflow_dispatch:       # Manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update README with recent activity
        uses: Readme-Workflows/recent-activity@v2.4.0
        with:
          GH_USERNAME: nightfury3128
          COMMIT_MSG: "⚡ Update README with the recent activity"
          MAX_LINES: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
