name: Recent Activity

on:
  schedule:
    - cron: "0 */6 * * *"   # Runs every 6 hours
  workflow_dispatch:        # Allow manual trigger

permissions:
  contents: write
  actions: read

jobs:
  update-activity:
    runs-on: ubuntu-latest
    name: Update recent activity
    steps:
      - uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: Readme-Workflows/recent-activity@v2.4.0
        with:
          GH_USERNAME: nightfury3128
          CONFIG_FILE: ".github/recent-activity.config.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
