name: Update PlayStation Activity

on:
  schedule:
    - cron: '0 8 * * *'   # runs every day at 8:00 UTC
  workflow_dispatch:        # allows you to trigger it manually

jobs:
  update-psn-activity:
    runs-on: ubuntu-latest
    name: Update PlayStation Gaming Activity
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install PSN API dependencies
        run: |
          npm init -y
          npm install psn-api axios dotenv

      - name: Fetch PSN Gaming Data
        id: psn_data
        env:
          PSN_ACCESS: ${{ secrets.PSN_ACCESS }}
        run: |
          # (same long script block I gave you before)
          # paste that entire block here unchanged
          echo "✅ PSN data fetched and formatted"

      - name: Update README with PSN Data
        run: |
          python3 << 'PYTHON_SCRIPT'
          import re
          with open('README.md', 'r', encoding='utf-8') as f:
              content = f.read()
          with open('psn_data.txt', 'r', encoding='utf-8') as f:
              psn_content = f.read().strip()
          pattern = r'(<!--PSN_ACTIVITY:start-->).*?(<!--PSN_ACTIVITY:end-->)'
          replacement = r'\1\n' + psn_content + r'\n\2'
          updated = re.sub(pattern, replacement, content, flags=re.DOTALL)
          with open('README.md', 'w', encoding='utf-8') as f:
              f.write(updated)
          print("✅ README updated with PSN data")
          PYTHON_SCRIPT

      - name: Update workflow status badge
        run: |
          python3 << 'PYTHON_SCRIPT'
          import json, re
          meta = json.load(open('psn_meta.json'))
          level = int(meta.get('level', 0))
          trophies = int(meta.get('totalTrophies', 0))
          content = open('README.md','r',encoding='utf-8').read()
          content = re.sub(
              r'<img src="https://img\.shields\.io/badge/PSN%20Level-[^"]+?"[^>]*>',
              f'<img src="https://img.shields.io/badge/PSN%20Level-{level}-blue?style=for-the-badge&logo=playstation" alt="PSN Level" />',
              content
          )
          content = re.sub(
              r'<img src="https://img\.shields\.io/badge/Trophies-[^"]+?"[^>]*>',
              f'<img src="https://img.shields.io/badge/Trophies-{trophies}-gold?style=for-the-badge&logo=playstation" alt="Total Trophies" />',
              content
          )
          with open('README.md','w',encoding='utf-8') as f: f.write(content)
          print(f"✅ Updated badges → Level {level}, Trophies {trophies}")
          PYTHON_SCRIPT

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "PlayStation Bot"
          git add README.md
          if git diff --staged --quiet; then
            echo "No PSN changes to commit"
          else
            git commit -m "🎮 Update PlayStation gaming activity [skip ci]"
            for i in 1 2 3; do
              git push && break || { echo "⚠️ Push failed, retrying ($i/3)"; git pull --rebase origin main; sleep 5; }
            done
          fi

      - name: Cleanup
        run: |
          rm -f fetch_psn_data.js psn_output.txt psn_data.txt psn_meta.json package.json package-lock.json
          rm -rf node_modules
